### ISSUE TITLE
CTRL+ALT+T Open terminal in linux

### ISSUE THREAD

**Issue by jesustejerina** [alfredbirk/tailwind-documentation#3]
Hi,

CTRL+ALT+T Open terminal in linux. Please change combination keys for linux. Thanks.

**Comment by alfredbirk** [comment]
Good point, will change it 👍

**Comment by alfredbirk** [comment]
I decided to leave it as it is since many people already have downloaded it and use the default binding. Apologies to Linux users. They can however manually change the keybinding.
