### ISSUE TITLE
Just an empty tab

### ISSUE THREAD

**Issue by sussweb** [alfredbirk/tailwind-documentation#7]
If a open tailwind documentation it just opens an empty tab. Is it broken?

**Comment by thomo** [comment]
same issue here

- VSC Version: 1.77.3 (Universal)
- macOs 12.6.2

**Comment by IgorWeisss** [comment]
Same for me!

**Comment by Nifled** [comment]
I'm also having this issue on a fresh install of vscode, so this is probably common. I was just about to uninstall this extension immediately, but I figured I might as well come and report it on here before

**Comment by alfredbirk** [comment]
Hi, thanks for reporting! I don't have the problem myself, which makes it hard to find a fix. How do you trigger the extension? With the hotkey? Does it also happen if you trigger it through the run command (i.e cmd+shift+p then type "tailwind documentation search")?

For reference, I use:
- Version: 1.77.3
- macOs 13.3

If anyone who has this error wants to help, could you try launching the extension locally? Do this by cloning the repo and going to "Run and debug > Launch extension". Maybe you see some error in the terminal?

**Comment by thomo** [comment]
Some new insights: 
- When I run the plugin direct in VSCode it works as expected, but when I use a dev container it shows just an empty page.
- I also try to run the extension in a dev container as mentioned by @alfredbirk but I can not see any error message. My guess is that some port(s) are blocked or not "connected".

**Comment by alfredbirk** [comment]
Thanks @thomo, I was able to reproduce the error in a dev container. And I could see a 401 error in the developer tools console when opening the extension.

The problem should now be fixed in V. 0.1.7 ✅  It would be great if someone who had the error could confirm.

**Comment by Nifled** [comment]
Just re-installed the extension and it works on my end! Thanks to everyone

**Comment by thomo** [comment]
I can confirm, it works. Thanks a lot.
PS: @alfredbirk How did you open the developer tools console? Did you open the tab in a browser? How?

**Comment by alfredbirk** [comment]
> I can confirm, it works. Thanks a lot.
> 
> PS: @alfredbirk How did you open the developer tools console? Did you open the tab in a browser? How?

You can do it inside of vscode. Open the command palette (cmd + shift + p) and type "Toggle developer tools".

**Comment by sussweb** [comment]
Yes. Works for me as well! Thank's a lot 👍
